name: kyma-project.io/kyma-runtime/kcp-components/keb-sap
team: kyma/gopher
images:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:1.35.20
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:1.35.20
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:1.35.20
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-expirator-job:1.35.20
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:1.35.20
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-sync:1.35.20
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker-schema-migrator:1.35.20
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-service-binding-cleanup-job:1.35.20
