# Build image
FROM --platform=$BUILDPLATFORM golang:1.27.1-alpine3.24 AS build

WORKDIR /go/src/github.com/kyma-project/kyma-environment-broker

COPY go.mod go.sum ./
RUN go mod download

COPY cmd cmd
COPY common common
COPY internal internal

ARG TARGETOS TARGETARCH
ARG BIN
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOFIPS140=v1.0.0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /bin/main ./cmd/${BIN}/main.go

# Get latest CA certs
FROM alpine:3.24.2 AS certs
RUN apk --update add ca-certificates

# Final image
FROM scratch
ENV GODEBUG=fips140=only,tlsmlkem=0
LABEL source=git@github.com:kyma-project/kyma-environment-broker.git

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /bin/main /bin/main
