// Code generated by mockery v2.53.4. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// QuotaClient is an autogenerated mock type for the QuotaClient type
type QuotaClient struct {
	mock.Mock
}

// GetQuota provides a mock function with given fields: subAccountID, planName
func (_m *QuotaClient) GetQuota(subAccountID string, planName string) (int, error) {
	ret := _m.Called(subAccountID, planName)

	if len(ret) == 0 {
		panic("no return value specified for GetQuota")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return rf(subAccountID, planName)
	}
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(subAccountID, planName)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(subAccountID, planName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuotaClient creates a new instance of QuotaClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuotaClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuotaClient {
	mock := &QuotaClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
