name: Build e2e provisioning test image

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-e2e-provisioning-test-image.yaml"
      - "testing/e2e/provisioning/**"
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - ".github/workflows/build-e2e-provisioning-test-image.yaml"
      - "testing/e2e/provisioning/**"

permissions:
  id-token: write
  contents: read 

jobs:
  restricted-gate:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    environment: restricted
    steps:
      - run: echo "Build approved"

  e2e-provisioning-test-image:
    needs: restricted-gate
    if: always() && (needs.restricted-gate.result == 'success' || needs.restricted-gate.result == 'skipped')
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@5e3584e7419fd4b566a29fdd6a1154b16a35e731
    with:
      name: e2e-provisioning-test
      dockerfile: Dockerfile
      context: testing/e2e/provisioning
