name: Validate Notable Changes

on:
  pull_request:
    paths:
      - 'notable-changes-to-release/**'

permissions:
  contents: read

jobs:
  validate-notable-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Validate notable changes md file
        run: "./scripts/notable_changes_validate.sh"
