name: Verify KEB - Go

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**.md"
      - "component-config.yaml"
  
permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  run-go-tests:
    uses: "./.github/workflows/run-unit-tests-reusable.yaml"

  run-go-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Set up go environment
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version-file: 'go.mod'
        
    - name: Go linter
      env:
        GOLINT_TIMEOUT: ${{ vars.GOLINT_TIMEOUT }}
      run: make go-lint

  run-go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up go environment
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: 'go.mod'

      - name: Run go checks
        run: make checks
