name: Run govulncheck

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - "component-config.yaml"

jobs:
  run-govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Run govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f
        with:
          go-version-file: 'go.mod'
          repo-checkout: false
